#!/bin/bash

# First su in as root
#sudo su

# Then set fan control to manual mode
# ODD
echo 1400 > /sys/devices/platform/applesmc.768/fan1_min

# HDD
echo 1100 > /sys/devices/platform/applesmc.768/fan2_min

# CPU
echo 1200 > /sys/devices/platform/applesmc.768/fan3_min
